server:
  port: 9094

spring:
  application:
    name: Book library
  mvc:
    favicon:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          hbm2ddl:
            auto: create
            show_sql: true
datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  continue-on-error: false
  generate-unique-name: true
  username: sa
  password:
h2:
  console:
    enabled: true
library:
  url: https://www.googleapis.com/books/v1/volumes
  key: AIzaSyDIsbsXe7G1OkrFcGsgi_cAGGRiQ1gC_lI
